Fix script

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -20,7 +20,7 @@ download_release "$ASDF_INSTALL_VERSION" "$release_file"
 if [ "$format" == tar.gz ]; then
 	tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
 else
-	unzip "$release_file" -d "$ASDF_DOWNLOAD_PATH" -o || fail "Could not extract $release_file"
+	unzip -o "$release_file" -d "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
 fi
 
 # Remove the archive file since we don't need to keep it
